### ISSUE TITLE
Port-problemer med secure-logs-fluentd

### ISSUE THREAD

**Issue by Kyrremann** [nais/ginuudan#1]
Når vi prøver å skru av secure-logs-fluentd så får vi følgende feilmelding ved port-forward, men får skrudd kontaineren.

```
{"message": "Port 24444 has the following error: error forwarding port 24444 to pod 2d9237b680cdb8db9fcec68afc6adcfa4a8c8f0bd8338166ad8b1364d6aa3fd1, uid : exit status 1: 2021/07/12 08:47:06 socat[1660178] E connect(5, AF=2 127.0.0.1:24444, 16): Connection refused\n", "timestamp": "2021-07-12T08:47:06.950692+00:00", "object": {"apiVersion": "v1", "kind": "Pod", "name": "pi-8dqrm", "uid": "78176309-a1dd-4749-8065-238849b848dc", "namespace": "aura"}, "severity": "error"}
```

Job-spec som kan brukes ved testing (må brukes on-prem):
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  labels:
    app: pi
spec:
  template:
    metadata:
      annotations:
        ginuudan.nais.io/dwindle: "true"
    spec:
      restartPolicy: Never
      containers:
      - name: pi
        image: navikt/perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"]
      - name: secure-logs-fluentd
        image: docker.pkg.github.com/nais/nais-logd/nais-logd:103
        volumeMounts:
          - name:      "secure-logs"
            mountPath: "/secure-logs"
          - name:      "secure-logs-config"
            mountPath: "/fluentd/etc"
            readOnly:  true
          - name:      "ca-bundle-pem"
            mountPath: "/etc/pki/tls/certs/ca-bundle.crt"
            subPath:   "ca-bundle.pem"
            readOnly:  true
      - name: secure-logs-configmap-reload
        image: jimmidyson/configmap-reload@sha256:befec9f23d2a9da86a298d448cc9140f56a457362a7d9eecddba192db1ab489e
        args:
          - --volume-dir=/config
          - --webhook-url=http://localhost:24444/api/config.reload
          - --webhook-method=GET
        volumeMounts:
          - name:      "secure-logs-config"
            mountPath: "/config"
            readOnly:  true
      volumes:
        - name: "secure-logs"
          emptyDir:
            sizeLimit: "128M"
        - name: "secure-logs-config"
          configMap:
            name: "secure-logs"
        - name: ca-bundle-pem
          configMap:
            name: ca-bundle-pem
```
